---
title: "NYfood"
output:
  html_document:
    df_print: paged
---


```{r include=FALSE}
library(mongolite)
library(glue)
library(jsonlite)
library(memisc)
library(ggplot2)
library(ggmap)
library(sf)
library(tidyverse)
library(leaflet)
library(leaflet.providers)
library(htmltools)
library(scales)
```

```{r include=FALSE}
url1="mongodb+srv://etudiant:ur2@clusterm1.0rm7t.mongodb.net/food"
coll<-mongo("NYfood",url=url1,options = ssl_options(allow_invalid_hostname=TRUE, weak_cert_validation=TRUE))
```


```{r include=FALSE}
food<-coll$find(query = '{"grades":{"$not":{"$eq":{"$size":0}}},"borough":"Manhattan","cuisine":"Asian","grades.grade":{"$not":{"$eq":"Not Yet Graded"}}}',fields='{"address":true,"name":true}')
longlat<-as.character(food[,2][,2][,2])
food["lat"]<-substr(longlat,3,12)
food["lon"]<-str_replace(str_replace(substr(longlat,14,21),", ","")," ","")

food
```

```{r include=FALSE, warning=FALSE}
food2<-coll$aggregate('[
{"$match":{"grades":{"$not":{"$eq":{"$size":0}}},"cuisine":"Asian","borough":"Manhattan","grades.grade":{"$not":{"$eq":"Not Yet Graded"}}}},
{"$unwind":"$grades"},
{"$group":{"_id": "$_id","score": {"$avg": "$grades.score"}}}
]')

food3<-merge(food,food2)
```





## Les restaurants asiatiques de Manhattan 

Les notes sont décroissantes, plus la note est petite, meilleure le restaurant est. Les restaurants qui ont les meilleures notes sont en vert, ceux qui ont les moins bonnes sont en rouge. 
Lorsque vous cliquez sur un restaurant, son nom et son score apparaissent.



```{r echo=FALSE, warning=FALSE}

ColorPal2 <- colorNumeric(scales::seq_gradient_pal(low = "green", high = "red", 
                                               space = "Lab"), domain = c(0,40))
food3$col<-ColorPal2(food3$score)


leaflet(data = food3) %>% addTiles() %>%
  addCircleMarkers(~as.double(lat),~as.double(lon),popup=~paste("<p> <b>Nom :</b>", name,"</p>","<p> <b>Note : </b>", score,"</p>"  ),color=~col) %>% setView(lng = food3$lat[1], lat = food3$lon[1], zoom = 12)
```

























